// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox (
    id,
    aggregate_type,
    aggregate_id,
    event_type,
    event_version,
    payload,
    topic,
    tracing_context,
    status
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, 'PENDING'
         )
`

type CreateOutboxEventParams struct {
	ID             uuid.UUID       `json:"id"`
	AggregateType  string          `json:"aggregate_type"`
	AggregateID    string          `json:"aggregate_id"`
	EventType      string          `json:"event_type"`
	EventVersion   int32           `json:"event_version"`
	Payload        json.RawMessage `json:"payload"`
	Topic          string          `json:"topic"`
	TracingContext json.RawMessage `json:"tracing_context"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.EventVersion,
		arg.Payload,
		arg.Topic,
		arg.TracingContext,
	)
	return err
}

const deleteOldOutboxEvents = `-- name: DeleteOldOutboxEvents :exec
DELETE FROM outbox
WHERE status IN ('PUBLISHED', 'FAILED')
  -- O cast ::text força o SQLC a gerar o argumento como string no Go
  AND created_at < NOW() - ($1::text)::interval
`

func (q *Queries) DeleteOldOutboxEvents(ctx context.Context, interval string) error {
	_, err := q.db.ExecContext(ctx, deleteOldOutboxEvents, interval)
	return err
}

const fetchPendingOutboxEvents = `-- name: FetchPendingOutboxEvents :many
SELECT id, event_type, aggregate_id, event_version, payload, topic, tracing_context
FROM outbox
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type FetchPendingOutboxEventsRow struct {
	ID             uuid.UUID       `json:"id"`
	EventType      string          `json:"event_type"`
	AggregateID    string          `json:"aggregate_id"`
	EventVersion   int32           `json:"event_version"`
	Payload        json.RawMessage `json:"payload"`
	Topic          string          `json:"topic"`
	TracingContext json.RawMessage `json:"tracing_context"`
}

func (q *Queries) FetchPendingOutboxEvents(ctx context.Context, limit int32) ([]FetchPendingOutboxEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPendingOutboxEventsRow
	for rows.Next() {
		var i FetchPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.EventVersion,
			&i.Payload,
			&i.Topic,
			&i.TracingContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxAsFailed = `-- name: MarkOutboxAsFailed :exec
UPDATE outbox
SET status = 'FAILED',
error_msg = $2,
retry_count = retry_count + 1,
updated_at = NOW()
WHERE id = $1
`

type MarkOutboxAsFailedParams struct {
	ID       uuid.UUID      `json:"id"`
	ErrorMsg sql.NullString `json:"error_msg"`
}

func (q *Queries) MarkOutboxAsFailed(ctx context.Context, arg MarkOutboxAsFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxAsFailed, arg.ID, arg.ErrorMsg)
	return err
}

const markOutboxAsProcessing = `-- name: MarkOutboxAsProcessing :exec
UPDATE outbox
SET status = 'PROCESSING', updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkOutboxAsProcessing(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOutboxAsProcessing, pq.Array(ids))
	return err
}

const markOutboxAsPublished = `-- name: MarkOutboxAsPublished :exec
UPDATE outbox
SET status = 'PUBLISHED', published_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxAsPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markOutboxAsPublished, id)
	return err
}

const resetStuckEvents = `-- name: ResetStuckEvents :exec
UPDATE outbox
SET status = 'PENDING', error_msg = 'stuck_recovery'
WHERE status = 'PROCESSING'
  AND updated_at < NOW() - ($1::text)::interval
`

func (q *Queries) ResetStuckEvents(ctx context.Context, interval string) error {
	_, err := q.db.ExecContext(ctx, resetStuckEvents, interval)
	return err
}
