// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/infra/grpc/protofiles/fleet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDriverRequest) Reset() {
	*x = SearchDriverRequest{}
	mi := &file_internal_infra_grpc_protofiles_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDriverRequest) ProtoMessage() {}

func (x *SearchDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_protofiles_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDriverRequest.ProtoReflect.Descriptor instead.
func (*SearchDriverRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_protofiles_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *SearchDriverRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type SearchDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDriverResponse) Reset() {
	*x = SearchDriverResponse{}
	mi := &file_internal_infra_grpc_protofiles_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDriverResponse) ProtoMessage() {}

func (x *SearchDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_protofiles_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDriverResponse.ProtoReflect.Descriptor instead.
func (*SearchDriverResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_protofiles_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *SearchDriverResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *SearchDriverResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchDriverResponse) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *SearchDriverResponse) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_internal_infra_grpc_protofiles_fleet_proto protoreflect.FileDescriptor

const file_internal_infra_grpc_protofiles_fleet_proto_rawDesc = "" +
	"\n" +
	"*internal/infra/grpc/protofiles/fleet.proto\x12\x02pb\"0\n" +
	"\x13SearchDriverRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"k\n" +
	"\x14SearchDriverResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x04 \x01(\x01R\x03lng2Q\n" +
	"\fFleetService\x12A\n" +
	"\fSearchDriver\x12\x17.pb.SearchDriverRequest\x1a\x18.pb.SearchDriverResponseB\x18Z\x16internal/infra/grpc/pbb\x06proto3"

var (
	file_internal_infra_grpc_protofiles_fleet_proto_rawDescOnce sync.Once
	file_internal_infra_grpc_protofiles_fleet_proto_rawDescData []byte
)

func file_internal_infra_grpc_protofiles_fleet_proto_rawDescGZIP() []byte {
	file_internal_infra_grpc_protofiles_fleet_proto_rawDescOnce.Do(func() {
		file_internal_infra_grpc_protofiles_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_protofiles_fleet_proto_rawDesc), len(file_internal_infra_grpc_protofiles_fleet_proto_rawDesc)))
	})
	return file_internal_infra_grpc_protofiles_fleet_proto_rawDescData
}

var file_internal_infra_grpc_protofiles_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_infra_grpc_protofiles_fleet_proto_goTypes = []any{
	(*SearchDriverRequest)(nil),  // 0: pb.SearchDriverRequest
	(*SearchDriverResponse)(nil), // 1: pb.SearchDriverResponse
}
var file_internal_infra_grpc_protofiles_fleet_proto_depIdxs = []int32{
	0, // 0: pb.FleetService.SearchDriver:input_type -> pb.SearchDriverRequest
	1, // 1: pb.FleetService.SearchDriver:output_type -> pb.SearchDriverResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_infra_grpc_protofiles_fleet_proto_init() }
func file_internal_infra_grpc_protofiles_fleet_proto_init() {
	if File_internal_infra_grpc_protofiles_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_protofiles_fleet_proto_rawDesc), len(file_internal_infra_grpc_protofiles_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_grpc_protofiles_fleet_proto_goTypes,
		DependencyIndexes: file_internal_infra_grpc_protofiles_fleet_proto_depIdxs,
		MessageInfos:      file_internal_infra_grpc_protofiles_fleet_proto_msgTypes,
	}.Build()
	File_internal_infra_grpc_protofiles_fleet_proto = out.File
	file_internal_infra_grpc_protofiles_fleet_proto_goTypes = nil
	file_internal_infra_grpc_protofiles_fleet_proto_depIdxs = nil
}
